const initState = {
    board: {},
    pieces: {
        w_R0: {
            start_pos: 0,
            curr_pos: 0,
            feasible_moves: [],
            moves: [8, 1, -1, -8],
        },
        w_K0: {
            start_pos: 1,
            curr_pos: 1,
            feasible_moves: [],
            moves: [6, 10, 15, 17, -6, -10, -15, -17],
        },
        w_B0: {
            start_pos: 2,
            curr_pos: 2,
            feasible_moves: [],
            moves: [-8, -9, -7, 7, 8, 9],
        },
        w__K: {
            start_pos: 3,
            curr_pos: 3,
            feasible_moves: [],
            moves: [7, 8, 9, -1, 1, -7, -8, -9],
        },
        w__Q: {
            start_pos: 4,
            curr_pos: 4,
            feasible_moves: [],
            moves: [-9, -8, -7, -1, 1, 7, 8, 9],
        },
        w_B1: {
            start_pos: 5,
            curr_pos: 5,
            feasible_moves: [],
            moves: [-7, -9, 7, 9],
        },
        w_K1: {
            start_pos: 6,
            curr_pos: 6,
            feasible_moves: [],
            moves: [6, 10, 15, 17, -6, -10, -15, -17],
        },
        w_R1: {
            start_pos: 7,
            curr_pos: 7,
            feasible_moves: [],
            moves: [8, -1, 1, -8],
        },
        w_P0: { start_pos: 8, curr_pos: 8, feasible_moves: [], moves: [7, 8, 9] },
        w_P1: { start_pos: 9, curr_pos: 9, feasible_moves: [], moves: [7, 8, 9] },
        w_P2: { start_pos: 10, curr_pos: 10, feasible_moves: [], moves: [7, 8, 9] },
        w_P3: { start_pos: 11, curr_pos: 11, feasible_moves: [], moves: [7, 8, 9] },
        w_P4: { start_pos: 12, curr_pos: 12, feasible_moves: [], moves: [7, 8, 9] },
        w_P5: { start_pos: 13, curr_pos: 13, feasible_moves: [], moves: [7, 8, 9] },
        w_P6: { start_pos: 14, curr_pos: 14, feasible_moves: [], moves: [7, 8, 9] },
        w_P7: { start_pos: 15, curr_pos: 15, feasible_moves: [], moves: [7, 8, 9] },
        b_P0: {
            start_pos: 48,
            curr_pos: 48,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P1: {
            start_pos: 49,
            curr_pos: 49,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P2: {
            start_pos: 50,
            curr_pos: 50,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P3: {
            start_pos: 51,
            curr_pos: 51,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P4: {
            start_pos: 52,
            curr_pos: 52,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P5: {
            start_pos: 53,
            curr_pos: 53,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P6: {
            start_pos: 54,
            curr_pos: 54,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_P7: {
            start_pos: 55,
            curr_pos: 55,
            feasible_moves: [],
            moves: [-7, -8, -9],
        },
        b_R0: {
            start_pos: 56,
            curr_pos: 56,
            feasible_moves: [],
            moves: [-8, -1, 1, 8],
        },
        b_K0: {
            start_pos: 57,
            curr_pos: 57,
            feasible_moves: [],
            moves: [-6, -10, -15, -17, 6, 10, 15, 17],
        },
        b_B0: {
            start_pos: 58,
            curr_pos: 58,
            feasible_moves: [],
            moves: [-9, -7, 7, 9],
        },
        b__K: {
            start_pos: 59,
            curr_pos: 59,
            feasible_moves: [],
            moves: [-7, -8, -9, -1, 1, 7, 8, 9],
        },
        b__Q: {
            start_pos: 60,
            curr_pos: 60,
            feasible_moves: [],
            moves: [-9, -8, -7, -1, 1, 7, 8, 9],
        },
        b_B1: {
            start_pos: 61,
            curr_pos: 61,
            feasible_moves: [],
            moves: [-9, -7, 7, 9],
        },
        b_K1: {
            start_pos: 62,
            curr_pos: 62,
            feasible_moves: [],
            moves: [-6, -10, -15, -17, 6, 10, 15, 17],
        },
        b_R1: {
            start_pos: 63,
            curr_pos: 63,
            feasible_moves: [],
            moves: [-8, -1, 1, 8],
        },
    },
};

export default initState;